### ISSUE TITLE
uninitialized constant Repository::GitBackend

### ISSUE THREAD

**Issue by bndbsh** [rosenfeld/gitorious-cookbooks#13] opened 2011-11-01 00:40 UTC
Hi,

Installation runs without a hitch, but creating repositories fails with this in message_processing.log:

Processor: Repository(6)::create_git_repository(["812/73d/8aa99161b5b426430c50e72fbca16f47bc.git"]..)
RepositoryCreationProcessor::on_error: NameError raised: uninitialized constant Repository::GitBackend
RepositoryCreationProcessor::on_error: ActiveMessaging::AbortMessageException raised: ActiveMessaging::AbortMessageException
Processor:process! - AbortMessageException caught.

Which I imagine is initially raised from repository.rb. $LOAD_PATH seems to be okay and I even tried explicitly requiring git_backend, nothing. I'm not familiar enough with Rails 2 to debug any further.

**Comment by rosenfeld** [comment] 2011-11-01 13:53
What Git source are you pointing to in your node.json? I can try to reproduce here when I find some time...

**Comment by bndbsh** [comment] 2011-11-01 14:22
``` javascript
     "git": {
       "url": "git://gitorious.org/gitorious/mainline.git",
       "reference": "v2.0.2"
     },
```

**Comment by rosenfeld** [comment] 2011-11-01 15:01
Ok, when I find some time, I'll give it a try

**Comment by rosenfeld** [comment] 2011-11-01 15:19
Anyway, this is interesting:

<pre>
Processor: Repository(6)::create_git_repository(["812/73d/8aa99161b5b426430c50e72fbca16f47bc.git"]..)
RepositoryCreationProcessor::on_error: NameError raised: uninitialized constant Repository::GitBackend
</pre>


Repository::GitBackend should be defined in lib/git_backend.rb. Do you have this file? Take a look at its content. Make sure there's nothing wrong with your git checkout. You can also request for help in the Gitorious mailing list.

**Comment by rosenfeld** [comment] 2011-11-01 15:20
Actually, GitBackend should be defined there. The message warns about Repository::GitBackend because it looks inside the class Repository... What Ruby version are you using?

**Comment by bndbsh** [comment] 2011-11-01 15:28
ruby 1.8.7 (2010-01-10 patchlevel 249) [i486-linux]

GitBackend is indeed defined in that file, which is why I tried adding a require 'git_backend' in repository.rb

**Comment by bndbsh** [comment] 2011-11-01 15:31
In addition, I get this when I run script/console:
Loading production environment (Rails 2.3.5)
/var/rails/gitorious/config/../vendor/rails/railties/lib/initializer.rb:902:in `read':Errno::EACCES: Permission denied - /var/rails/gitorious/config/database.yml
/var/rails/gitorious/vendor/rails/activesupport/lib/active_support/dependencies.rb:440:in`load_missing_constant':NameError: uninitialized constant Grit::GitRuby

**Comment by rosenfeld** [comment] 2011-11-01 15:37
Try this: "chown -R git:git /var/rails/gitorious". I've seen you've changed the default installation directory...

**Comment by rosenfeld** [comment] 2011-11-01 15:37
And try running the console using the "git" account

**Comment by bndbsh** [comment] 2011-11-01 15:46
No errors if I run as git. Permissions were already properly set to git:git. Isn't apache running as www-data? Could that be a problem?

**Comment by rosenfeld** [comment] 2011-11-01 15:48
If you're using Passenger, it will run the application as the owner of the folder as far as I know, so "ps aux|grep rails" should show you the git user. Can you check that? Unless you've specified the user manually in the passenger configuration...

**Comment by rosenfeld** [comment] 2011-11-01 15:50
I'll probably need your entire node.json for replicating your problem... Just remove the password lines or change them and send it to me...

**Comment by bndbsh** [comment] 2011-11-01 15:58
http://paste2.org/p/1752172

"ps aux|grep rails" shows git running rails on gitorious.

**Comment by rosenfeld** [comment] 2011-11-01 16:02
And what modifications have you done for your code to be hosted under /var/rails/gitorious?

**Comment by bndbsh** [comment] 2011-11-01 16:06
Simply changed /etc/apache2/sites-enabled/gitorious.conf and gitorious-ssl to point to the new location.

**Comment by rosenfeld** [comment] 2011-11-01 16:11
So, you have just "mv /var/www/gitorious /var/rails/gitorious"? Not sure if that would be enough...

**Comment by rosenfeld** [comment] 2011-11-01 16:12
It would be better to change the recipe for allowing this directory to be customizable and make sure the recipe will keep working...

**Comment by bndbsh** [comment] 2011-11-01 16:14
Yes, but I don't have a clue how to do that. Are you sure the issue is caused by the directory change?

**Comment by rosenfeld** [comment] 2011-11-01 16:16
Lots of people are claiming their Gitorious install is working properly by using this recipe and it always worked for me. So, this is definetely something I would suspect about. Have you tried running the recipe with no extra customization?

**Comment by bndbsh** [comment] 2011-11-01 16:18
I didn't change the directory immediately, but I don't recall if it was before or after encountering this bug. I'll try without the change to make sure.

**Comment by bndbsh** [comment] 2011-11-01 16:25
Well look at that, moving back to /var/www/gitorious worked. Now just need to figure out why...

Thanks for the help!

**Comment by rosenfeld** [comment] 2011-11-01 16:40
Ok. So, I'm closing this issue. Try running "grep -RI www cookbooks" to understand where it is used...

**Closed as completed by rosenfeld** 2011-11-01 16:40 UTC
